#!/bin/bash
# configure-extensions.sh
# Validates the EXTENSIONS env var and writes shared_preload_libraries config.
# Sourced by docker-entrypoint-wrapper.sh — runs BEFORE PostgreSQL starts.

set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXTENSIONS_CONF="${SCRIPTS_DIR}/extensions.conf"
CONF_DIR="/etc/postgresql/conf.d"

# ---------------------------------------------------------------------------
# Parse supported extensions from the registry file
# ---------------------------------------------------------------------------
declare -A SUPPORTED_EXTENSIONS
declare -A PRELOAD_LIBRARIES
declare -A PG_EXTENSION_NAMES

while IFS=: read -r ext lib pgname; do
    # Skip comments and empty lines
    [[ "$ext" =~ ^[[:space:]]*# ]] && continue
    [[ -z "$ext" ]] && continue
    ext=$(echo "$ext" | xargs)   # trim whitespace
    lib=$(echo "$lib" | xargs)
    pgname=$(echo "${pgname:-}" | xargs)
    SUPPORTED_EXTENSIONS["$ext"]=1
    if [[ -n "$lib" ]]; then
        PRELOAD_LIBRARIES["$ext"]="$lib"
    fi
    # Map user-facing name to PG extension name (default: same as user name)
    PG_EXTENSION_NAMES["$ext"]="${pgname:-$ext}"
done < "$EXTENSIONS_CONF"

# ---------------------------------------------------------------------------
# Handle empty / unset EXTENSIONS
# ---------------------------------------------------------------------------
if [[ -z "${EXTENSIONS:-}" ]]; then
    echo "INFO: No EXTENSIONS specified. Starting PostgreSQL without additional extensions."
    mkdir -p "$CONF_DIR"
    echo "# No extensions configured" > "${CONF_DIR}/extensions.conf"
    return 0 2>/dev/null || exit 0
fi

# ---------------------------------------------------------------------------
# Parse and validate the comma-separated EXTENSIONS list
# ---------------------------------------------------------------------------
IFS=',' read -ra REQUESTED_EXTENSIONS <<< "$EXTENSIONS"

INVALID_EXTENSIONS=()
VALID_EXTENSIONS=()

for ext in "${REQUESTED_EXTENSIONS[@]}"; do
    ext=$(echo "$ext" | xargs)   # trim whitespace
    [[ -z "$ext" ]] && continue
    if [[ -z "${SUPPORTED_EXTENSIONS[$ext]+x}" ]]; then
        INVALID_EXTENSIONS+=("$ext")
    else
        VALID_EXTENSIONS+=("$ext")
    fi
done

if [[ ${#INVALID_EXTENSIONS[@]} -gt 0 ]]; then
    echo "=========================================="
    echo "ERROR: Invalid extension(s) requested:"
    for ext in "${INVALID_EXTENSIONS[@]}"; do
        echo "  ✗ $ext"
    done
    echo ""
    echo "Supported extensions:"
    for ext in $(echo "${!SUPPORTED_EXTENSIONS[@]}" | tr ' ' '\n' | sort); do
        echo "  • $ext"
    done
    echo "=========================================="
    exit 1
fi

if [[ ${#VALID_EXTENSIONS[@]} -eq 0 ]]; then
    echo "INFO: EXTENSIONS is set but contains no valid extension names."
    mkdir -p "$CONF_DIR"
    echo "# No extensions configured" > "${CONF_DIR}/extensions.conf"
    return 0 2>/dev/null || exit 0
fi

# ---------------------------------------------------------------------------
# Build shared_preload_libraries and write dynamic config
# ---------------------------------------------------------------------------
PRELOAD_LIST=()
for ext in "${VALID_EXTENSIONS[@]}"; do
    if [[ -n "${PRELOAD_LIBRARIES[$ext]+x}" ]]; then
        PRELOAD_LIST+=("${PRELOAD_LIBRARIES[$ext]}")
    fi
done

mkdir -p "$CONF_DIR"

{
    echo "# Auto-generated by configure-extensions.sh — do not edit"
    echo "# Extensions: ${VALID_EXTENSIONS[*]}"
    echo ""

    if [[ ${#PRELOAD_LIST[@]} -gt 0 ]]; then
        PRELOAD_STRING=$(IFS=','; echo "${PRELOAD_LIST[*]}")
        echo "shared_preload_libraries = '${PRELOAD_STRING}'"
    fi

    # pg_cron requires database name configuration
    for ext in "${VALID_EXTENSIONS[@]}"; do
        if [[ "$ext" == "pg_cron" ]]; then
            echo "cron.database_name = '${POSTGRES_DB:-postgres}'"
        fi
    done
} > "${CONF_DIR}/extensions.conf"

echo "INFO: Configured extensions: ${VALID_EXTENSIONS[*]}"
if [[ ${#PRELOAD_LIST[@]} -gt 0 ]]; then
    PRELOAD_STRING=$(IFS=','; echo "${PRELOAD_LIST[*]}")
    echo "INFO: shared_preload_libraries = '${PRELOAD_STRING}'"
fi

# Export for use by enable-extensions.sh
export VALIDATED_EXTENSIONS="${VALID_EXTENSIONS[*]}"

# Export PG extension name mapping (format: user_name=pg_name pairs)
PG_NAME_MAP=()
for ext in "${VALID_EXTENSIONS[@]}"; do
    PG_NAME_MAP+=("${ext}=${PG_EXTENSION_NAMES[$ext]}")
done
export PG_EXTENSION_MAP="${PG_NAME_MAP[*]}"
